server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/devraghavm/spring-cloud-config-server-repository
          username: devraghavm
          password: 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
          default-label: main
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: springCloud_Pwd!

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG