server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/devraghavm/spring-cloud-config-server-repository
          username: devraghavm
          password: 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
          default-label: main
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: '{cipher}3b3780080fb642ef40f63fb30bf175ec68820f8d90ed6914f4e6398cbb1b7167f8d691d7f7a3ec4e6d79e8a672a5dbf0'

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG